### PR TITLE
Target netstandards2.0 in ClassLib instead of netcoreapp2.0

### PR DESCRIPTION
**Pull request by ollejacobsen**
Target netstandards2.0 in ClassLib instead of netcoreapp2.0
Also updates AutoFixure to 4.4.0 due to the netstandards support.

### CODE REVIEW

**Comment by asser-dk** [comment]
Perfect! I was going to make the same pull request today

**Comment by ollejacobsen** [comment]
There are two tests that are failing. But they failed for the same reason when I ran them on **master** so I left them untouched.

**Comment by Shwetajain148** [comment]
Hi @ollejacobsen and @asser-dk, Do you mind telling me your use case/requirement here? Do you have to consume some existing .net framework assembly in your current application which require some framework related features and you opted .net standard? If so can you please let me know the exact framework version of your application?

Thanks for additional information.

**Comment by Shwetajain148** [comment]
Hi @asser-dk and @ollejacobsen, Can I please get some input from your side for my query above? 

Thanks!

**Comment by gregorylyons** [comment]
@Shwetajain148 At a guess; placing logging into a library used as a dependency in a .NET framework and a core application.

**Comment by petterl** [comment]
Hi @Shwetajain148, I'm in the same team as @ollejacobsen and the reason is that we have an old framework library that is ported to netstandard. This is included in other framework applications but will be included in netcore applications in the future.

We use loggly extensivly in the library currently and would love to do that in the future as well.
To have a lib targeting netstandard is a good thing since it can be consumed by both netstandard, netcore and framework projects.

**Comment by Shwetajain148** [comment]
Hi @petterl & @gregorylyons, Thanks for your inputs here. I'm certainly going to look at this PR soon and implement the right behavior. Currently I'm working on some other ongoing issues so need some time to switch over it. 

Thank you once again for being around.

**Comment by Shwetajain148** [comment]
Tested the PR and found working fine with both .NET Core and .NET Frameworks. Merging this one.

**Comment by petterl** [comment]
Great. When is a new release planned?

**Comment by Shwetajain148** [comment]
@petterl, I have released the beta package containing the new changes here- https://www.nuget.org/packages/log4net-loggly/8.0.1-beta. Feel free to test this out and report us back that how it goes. 

We are expecting some community feedback before publishing the final production release. Still for your question- The new production release is scheduled for the next week. 

Thanks!

**Comment by Shwetajain148** [comment]
Hey All, The new package containing .NET Standard support is in production now. Ref- https://www.nuget.org/packages/log4net-loggly/8.0.1

Thanks!

**Pull request merged**
